### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by doctoralvarez** [nexus-stc/stc#2]
On web site for STC error:
DatabaseClosedError: NotFoundError Table MetaDb not part of transaction NotFoundError: Table MetaDb not part of transaction NotFoundError: Table MetaDb not part of transaction NotFoundError: Table MetaDb not part of transaction

**Comment by the-superpirate** [comment]
Sorry, I was rolling unsuccessful update. Should be better now (or in 10-20 minutes, depends on caching)

**Comment by the-superpirate** [comment]
Feel free to re-open if the issue remains
