### ISSUE TITLE
I have a bug,

### ISSUE THREAD

**Issue by aazocar15** [nexus-stc/stc#3]
I can't download any more papers. Bot says i have a bug.
What do I do?

**Comment by aazocar15** [comment]
![image](https://github.com/nexus-stc/stc/assets/140347173/f85b162d-2935-43b0-ba0a-7418b834aa3d)

**Comment by aazocar15** [comment]
Please help, i have to do a research paper ... do this Friday

**Comment by the-superpirate** [comment]
Better to bring this kind of bugs to Telegram chat. Fixed.
