### ISSUE TITLE
Unable to seed - make the list public?

### ISSUE THREAD

**Issue by wowquester** [nexus-stc/stc#7]
Hi,
while trying to help this project, everytime I get just:
wait, we are generating file...
Oops! Something goes wrong and we are trying hard to revive. Please, try a little bit later.

This need to work. I am willing to give this project some TB, but i need something to share first. 

How about making the IPFS list a littlebit more public?..

**Comment by the-superpirate** [comment]
Are you speaking about `/seed` command in the bot? It has been fixed several days ago.
If you have multiple TB, the more relevant guide is https://standard--template--construct-org.ipns.dweb.link/#/help/replicate
