### ISSUE TITLE
STC doesn't work in firefox based browsers. 

### ISSUE THREAD

**Issue by wowquester** [nexus-stc/stc#8]
Hey,
although Safari seems to work just fine, in firefox, librewolf and TOR I just can't get past the loading screen. 

![Screenshot 2023-08-05 at 23 06 48](https://github.com/nexus-stc/stc/assets/138876396/b9a1b231-3e13-475d-bcf8-b83892e3b2e1)

Plugins are disabled. 

The proper functionality would be great since I am not willing to switch to another browser.

Thanks, keep up your work.

**Comment by the-superpirate** [comment]
I'm working in Firefox, it is all right. There is the known issue occuring on updating STC, you may have faced it.

Could you try to test it on clean? If you do not want to clean cookies, go to DevTools -> Storage -> IndexedDB and delete MetaDb and UserDb records there.
